---
apiVersion: v1
kind: Pod
metadata:
  name: manila-csi-nginx
spec:
  containers:
    - name: manila-csi-nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: manila-vol
          mountPath: /var/lib/www
  volumes:
    - name: manila-vol
      persistentVolumeClaim:
        claimName: manila-csi-pvc
        readOnly: false
