---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-csi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manila-csi-sc
