apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pool: 
      subnet: '192.168.1.0/24'
      pool: '192.168.1.14-192.168.1.30'
      aggregation: default
