apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: google-policy
spec:
  rules:
      # Requires authentication on requests from any hostname
    - host: "*"
      # Tells Ambassador Edge Stack to apply the Filter only on request to the quote /backend/get-quote/ endpoint
      path: /
      # Identifies which Filter to use for the path and host above
      filters:
        - name: google
