apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-cephfs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

#provisioner: cephfs.manila.csi.openstack.org
provisioner: manila.csi.openstack.org
allowVolumeExpansion: false
parameters:
  # Manila share type
  type: cephfs
  appendShareMetadata: "{\"autogrow\": \"80\"}"

  csi.storage.k8s.io/provisioner-secret-name: manila-csi-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-secrets
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system


