apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-cephfs-sc
#provisioner: cephfs.manila.csi.openstack.org
provisioner: manila.csi.openstack.org
allowVolumeExpansion: false
parameters:
  # Manila share type
  type: cephfs
  appendShareMetadata: "{\"autogrow\": \"80\"}"

  csi.storage.k8s.io/provisioner-secret-name: manila-csi-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-secrets
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manila-cephfs-sc

---
apiVersion: v1
kind: Pod
metadata:
  name: manila-cephfs-pod
spec:
  containers:
    - name: nginx-manila-cephfs
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: manila-sc-pvc
          mountPath: /var/lib/www
  volumes:
    - name: manila-sc-pvc
      persistentVolumeClaim:
        claimName: manila-cephfs-pvc
        readOnly: false
