annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 2.7.1
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.13.1
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.22
description: A web-based collaborative LaTeX editor
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/overleaf
icon: https://avatars.githubusercontent.com/u/6359919?s=200&v=4
keywords:
- overleaf
- sharelatex
kubeVersion: '>=1.16.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: overleaf
sources:
- https://github.com/overleaf/overleaf
version: 3.1.2
