# This YAML file contains nginx & csi cinder driver objects,
# which are necessary to run nginx with csi cinder driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc5
provisioner: cinder.csi.openstack.org
#allowedTopologies:
#- matchLabelExpressions:
 # - key: topology.cinder.csi.openstack.org/zone
  #  values:
   # - Persistent_02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc5

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-sc-pvc-5
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: pvcvol
  volumes:
  - name: pvcvol
    persistentVolumeClaim:
      claimName: pvc5
      readOnly: false
