apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-cinder
  annotations: 
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cinder.csi.openstack.org
parameters:
  availability: nova

