---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-csi-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs-csi-sc
