apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"port":80}],"selector":{"app":"nginx"},"type":"LoadBalancer"}}
    purelb.io/allocated-by: PureLB
    purelb.io/allocated-from: default
  creationTimestamp: "2022-04-05T20:32:46Z"
  name: nginx-service
  namespace: default
  resourceVersion: "235796"
  uid: 6801982a-ed34-41fb-b089-3446764381d6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.243.81
  clusterIPs:
  - 10.104.243.81
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31977
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.69.1.1
