apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost-risc                         # Chose the desired name
  namespace: mattermost
spec:
  size: 20users                               # Adjust to your requirements
  ingress:
    #enabled: true
    enabled: false
    #host: mattermost.risc.c3.ca       # Adjust to your domain
    #annotations:
     # kubernetes.io/ingress.class: nginx
  version: 6.0.1
  licenseSecret: ""                             # If you have created secret in step 1, put its name here
  fileStore:
    external:
      url: object-arbutus.cloud.computecanada.ca
      bucket: mattermost_risc
      secret: arbutus-object-keys
  mattermostEnv:
  - name: MM_FILESETTINGS_AMAZONS3SSE
    value: "true"
  - name: MM_FILESETTINGS_AMAZONS3SSL
    value: "true"
