---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-csi-nginx
spec:
  containers:
    - name: web-server
      image: docker.io/library/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-csi-pvc
        readOnly: false
