apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinder-csi-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-csi-sc
