apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-csi-config
  namespace: kube-system
data:
  manila.conf: |
    [DEFAULT]
    debug = true
    default_share_type = cephfs
    cephfs_mounter_type = kernel
    #[cephfs_native]
    #cephfs_cluster_name = 
    #cephfs_fs_name = cephfs
