apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: overleaf
    meta.helm.sh/release-namespace: overleaf
  creationTimestamp: "2022-10-25T16:15:16Z"
  labels:
    app.kubernetes.io/instance: overleaf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overleaf
    app.kubernetes.io/version: 2.7.1
    helm.sh/chart: overleaf-3.1.2
  name: overleaf
  namespace: overleaf
  resourceVersion: "110174541"
  uid: 57aa7e6d-5fe4-4f2e-a0cc-f7935eac9220
spec:
  clusterIP: 10.100.23.89
  clusterIPs:
  - 10.100.23.89
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: overleaf
    app.kubernetes.io/name: overleaf
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
